import TOML from "@iarna/toml";

export interface BidMeConfig {
  bidding: {
    schedule: "weekly" | "monthly";
    duration: number;
    minimum_bid: number;
    increment: number;
  };
  banner: {
    width: number;
    height: number;
    formats: string[];
    max_size: number;
  };
  approval: {
    mode: "auto" | "emoji";
    allowed_reactions: string[];
  };
  payment: {
    provider: "polar-own" | "bidme-managed";
    allow_unlinked_bids: boolean;
    unlinked_grace_hours: number;
  };
  enforcement: {
    require_payment_before_bid: boolean;
    strikethrough_unlinked: boolean;
  };
  content_guidelines: {
    prohibited: string[];
    required: string[];
  };
}

export const DEFAULT_CONFIG: BidMeConfig = {
  bidding: {
    schedule: "monthly",
    duration: 7,
    minimum_bid: 50,
    increment: 5,
  },
  banner: {
    width: 800,
    height: 100,
    formats: ["png", "jpg", "svg"],
    max_size: 200,
  },
  approval: {
    mode: "auto",
    allowed_reactions: ["👍"],
  },
  payment: {
    provider: "polar-own",
    allow_unlinked_bids: false,
    unlinked_grace_hours: 24,
  },
  enforcement: {
    require_payment_before_bid: false,
    strikethrough_unlinked: true,
  },
  content_guidelines: {
    prohibited: ["adult content", "gambling", "misleading claims"],
    required: ["alt text", "clear branding"],
  },
};

export function generateToml(config: BidMeConfig): string {
  const header = `# BidMe Configuration
# Generated by \`bidme init\`
# Documentation: https://github.com/nicepkg/bidme

`;

  const sections: string[] = [header];

  sections.push(`# Bidding schedule and pricing
[bidding]
schedule = "${config.bidding.schedule}"
duration = ${config.bidding.duration}
minimum_bid = ${config.bidding.minimum_bid}
increment = ${config.bidding.increment}
`);

  sections.push(`# Banner display constraints
[banner]
width = ${config.banner.width}
height = ${config.banner.height}
formats = ${JSON.stringify(config.banner.formats)}
max_size = ${config.banner.max_size}
`);

  sections.push(`# Bid approval settings
[approval]
mode = "${config.approval.mode}"
allowed_reactions = ${JSON.stringify(config.approval.allowed_reactions)}
`);

  sections.push(`# Payment configuration
[payment]
provider = "${config.payment.provider}"
allow_unlinked_bids = ${config.payment.allow_unlinked_bids}
unlinked_grace_hours = ${config.payment.unlinked_grace_hours}
`);

  sections.push(`# Enforcement rules
[enforcement]
require_payment_before_bid = ${config.enforcement.require_payment_before_bid}
strikethrough_unlinked = ${config.enforcement.strikethrough_unlinked}
`);

  sections.push(`# Content guidelines for banner submissions
[content_guidelines]
prohibited = ${JSON.stringify(config.content_guidelines.prohibited)}
required = ${JSON.stringify(config.content_guidelines.required)}
`);

  return sections.join("\n");
}

export function parseToml(tomlString: string): BidMeConfig {
  const parsed = TOML.parse(tomlString) as unknown as BidMeConfig;
  return parsed;
}
